[build]
builder = "nixpacks"

[deploy]
startCommand = "flask run --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"

[service]
internal_port = 8080
